name: less_cgi
description: A sample less compiler application.
version: 1.0.0
homepage: https://github.com/james18178/xf_less_compiler

environment:
  sdk: '>=2.3.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  logging: '>=0.11.0 <0.12.0'
  mockito: '>=1.0.0 <5.0.0'
  stack_trace: '>=1.7.2 <2.0.0'
  test: '>=0.12.20+2 <2.0.0'
dependencies:
  less_dart: ^2.3.8
  shelf: ^0.7.9
  shelf_body_parser: ^1.0.6
